#!/usr/bin/env node
/**
 * fetch-images.js — Tool script for the image-gen-agent
 *
 * Receives JSON on stdin:
 * {
 *   theme: string,
 *   count?: number,         // default 4
 *   width?: number,         // default 1920
 *   height?: number,        // default 1080
 *   type?: "ai" | "photo",  // default "ai"
 *   zones?: string[],       // ["hero", "card", "background", "cta"]
 *   style?: string,         // "cinematic", "digital art", etc.
 *   vibe?: string           // "dark", "retro", "neon", etc.
 * }
 *
 * Outputs JSON on stdout:
 * {
 *   images: [{ url, alt, zone, width, height }],
 *   animations_css: string  // ready-to-use CSS block
 * }
 */

import { readFileSync } from "fs";

// ── Read stdin ────────────────────────────────────────────────────────────────
let raw = "";
try {
  raw = readFileSync("/dev/stdin", "utf-8").trim();
} catch {
  // Windows fallback — read from process.stdin synchronously
  const chunks = [];
  try {
    process.stdin.resume();
    for await (const chunk of process.stdin) chunks.push(chunk);
    raw = Buffer.concat(chunks).toString("utf-8").trim();
  } catch {
    raw = "{}";
  }
}

let args = {};
try {
  args = JSON.parse(raw);
} catch {
  args = {};
}

const {
  theme = "nature",
  count = 4,
  width = 1920,
  height = 1080,
  type = "ai",
  zones = ["hero", "card", "card", "background"],
  style = "cinematic, photorealistic",
  vibe = "atmospheric",
} = args;

// ── Helpers ───────────────────────────────────────────────────────────────────

/** URL-encode a prompt for Pollinations.ai */
function encodePrompt(prompt) {
  return prompt
    .trim()
    .replace(/\s+/g, "+")
    .replace(/[^a-zA-Z0-9+,.-]/g, (c) => encodeURIComponent(c));
}

/** Derive a deterministic seed from the theme string */
function deriveSeed(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash * 31 + str.charCodeAt(i)) >>> 0;
  }
  return (hash % 90000) + 10000;
}

/** Zone-aware dimension defaults */
function zoneDims(zone) {
  switch (zone) {
    case "hero":       return { w: 1920, h: 1080 };
    case "background": return { w: 1600, h: 900  };
    case "card":       return { w: 800,  h: 600  };
    case "cta":        return { w: 1200, h: 400  };
    case "avatar":     return { w: 400,  h: 400  };
    default:           return { w: width, h: height };
  }
}

/** Generate copyright-safe prompt from theme + zone */
function buildPrompt(theme, zone, vibe, style) {
  const moodMap = {
    hero:       `wide angle cinematic shot, ${theme} theme, ${vibe} atmosphere, dramatic lighting, ${style}`,
    background: `aerial view, ${theme} theme, ${vibe} mood, dark atmospheric, ${style}`,
    card:       `close up detail, ${theme} theme, ${vibe}, ${style}`,
    cta:        `abstract ${theme} themed background, ${vibe} colors, ${style}`,
    avatar:     `stylized ${theme} themed portrait illustration, ${vibe}, ${style}`,
  };
  return moodMap[zone] ?? `${theme} themed image, ${vibe}, ${style}`;
}

/** Generate alt text */
function buildAlt(theme, zone) {
  const altMap = {
    hero:       `${theme} themed hero banner image — dramatic cinematic atmosphere`,
    background: `${theme} themed atmospheric background`,
    card:       `${theme} themed feature image`,
    cta:        `${theme} themed call-to-action banner background`,
    avatar:     `${theme} styled avatar illustration`,
  };
  return altMap[zone] ?? `${theme} themed image`;
}

// ── Build Image URLs ──────────────────────────────────────────────────────────

const seed = deriveSeed(theme);
const images = [];

// Normalize zones array to requested count
const normalizedZones = zones.slice(0, count);
while (normalizedZones.length < count) normalizedZones.push("card");

normalizedZones.forEach((zone, i) => {
  const { w, h } = zoneDims(zone);
  let url;

  if (type === "photo") {
    // Royalty-free stock photo via Unsplash Source
    const keyword = encodeURIComponent(theme.split(" ")[0]);
    const suffix = zone === "card" ? `,${i + 1}` : "";
    url = `https://source.unsplash.com/${w}x${h}/?${keyword}${suffix}`;
  } else {
    // AI-generated via Pollinations.ai (free, no key)
    const prompt = buildPrompt(theme, zone, vibe, style);
    const encoded = encodePrompt(prompt);
    const zoneSeed = seed + i * 13;
    url = `https://image.pollinations.ai/prompt/${encoded}?width=${w}&height=${h}&nologo=true&seed=${zoneSeed}`;
  }

  images.push({
    url,
    alt: buildAlt(theme, zone),
    zone,
    width: w,
    height: h,
  });
});

// ── Standard Animations CSS ───────────────────────────────────────────────────

const ANIMATIONS_CSS = `
/* ========================================================
   ANIMATIONS — generated by fetch-images tool
   Theme: ${theme} | Vibe: ${vibe}
   All animations respect prefers-reduced-motion.
   ======================================================== */

/* flicker — neon/horror light effect */
@keyframes flicker {
  0%,100%{opacity:1} 41%{opacity:0.9} 42%{opacity:0.35} 43%{opacity:0.9}
  90%{opacity:0.95} 91%{opacity:0.5} 92%{opacity:0.95}
}
.flicker { animation: flicker 3s linear infinite; }

/* float — gentle levitation for icons, badges */
@keyframes float {
  0%,100%{transform:translateY(0px)} 50%{transform:translateY(-14px)}
}
.float { animation: float 5s ease-in-out infinite; }

/* glitch — digital distortion for dark/tech themes */
@keyframes glitch {
  0%{text-shadow:2px 0 #f00,-2px 0 #0ff,0 0 transparent}
  20%{text-shadow:-3px 0 #f00,3px 0 #0ff}
  40%{text-shadow:2px 0 transparent}
  60%{text-shadow:-3px 0 #f00,3px 0 #0ff}
  80%{text-shadow:2px 0 #f00,-2px 0 #0ff}
  100%{text-shadow:none}
}
.glitch { animation: glitch 2.5s steps(1) infinite; }

/* fade-in-up — entry animation for sections, cards */
@keyframes fadeInUp {
  from{opacity:0;transform:translateY(28px)}
  to{opacity:1;transform:translateY(0)}
}
.fade-in-up             { animation: fadeInUp 0.7s cubic-bezier(0.22,1,0.36,1) forwards; }
.fade-in-up-delay-1     { animation: fadeInUp 0.7s 0.15s cubic-bezier(0.22,1,0.36,1) forwards; opacity:0; }
.fade-in-up-delay-2     { animation: fadeInUp 0.7s 0.30s cubic-bezier(0.22,1,0.36,1) forwards; opacity:0; }
.fade-in-up-delay-3     { animation: fadeInUp 0.7s 0.45s cubic-bezier(0.22,1,0.36,1) forwards; opacity:0; }

/* red-pulse — danger/horror glow on CTAs */
@keyframes redPulse {
  0%,100%{box-shadow:0 0 0 0 rgba(204,0,0,0.5)}
  70%{box-shadow:0 0 0 16px rgba(204,0,0,0)}
}
.red-pulse { animation: redPulse 2.2s ease-out infinite; }

/* neon-glow — sci-fi/cyber glowing text */
@keyframes neonGlow {
  0%,100%{text-shadow:0 0 5px currentColor,0 0 10px currentColor,0 0 20px currentColor}
  50%{text-shadow:0 0 10px currentColor,0 0 25px currentColor,0 0 50px currentColor}
}
.neon-glow { animation: neonGlow 2s ease-in-out infinite; }

/* scan-lines — CRT overlay for retro/horror themes */
.scan-lines::after {
  content:'';
  position:absolute;inset:0;
  background:repeating-linear-gradient(
    transparent,transparent 2px,
    rgba(0,0,0,0.07) 2px,rgba(0,0,0,0.07) 4px
  );
  pointer-events:none;
  z-index:1;
}

/* accent-pulse — versatile glow pulse using CSS variable */
@keyframes accentPulse {
  0%,100%{box-shadow:0 0 0 0 color-mix(in srgb,var(--color-accent) 50%,transparent)}
  70%{box-shadow:0 0 0 14px transparent}
}
.accent-pulse { animation: accentPulse 2s ease-out infinite; }

/* ---- prefers-reduced-motion overrides ---- */
@media (prefers-reduced-motion: reduce) {
  .flicker,.float,.glitch,.fade-in-up,.fade-in-up-delay-1,
  .fade-in-up-delay-2,.fade-in-up-delay-3,.red-pulse,
  .neon-glow,.accent-pulse {
    animation: none !important;
    opacity: 1 !important;
    transform: none !important;
  }
}
`.trim();

// ── Output ────────────────────────────────────────────────────────────────────

console.log(JSON.stringify({
  images,
  animations_css: ANIMATIONS_CSS,
  meta: {
    theme,
    vibe,
    type,
    seed,
    generated_at: new Date().toISOString(),
  },
}, null, 2));
